Document: nullfs
Title: Debian nullfs Manual
Author: <insert document author here>
Abstract: This manual describes what nullfs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nullfs/nullfs.sgml.gz

Format: postscript
Files: /usr/share/doc/nullfs/nullfs.ps.gz

Format: text
Files: /usr/share/doc/nullfs/nullfs.text.gz

Format: HTML
Index: /usr/share/doc/nullfs/html/index.html
Files: /usr/share/doc/nullfs/html/*.html
